# Generated by Django 4.2.7 on 2024-01-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('promo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='myapi/static/myapi/images/membres/')),
                ('ok_to_be_displayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_fr', models.CharField(max_length=100, null=True)),
                ('nom_en', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('description_fr', models.CharField(max_length=1000, null=True)),
                ('description_en', models.CharField(max_length=1000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='myapi/static/myapi/images/logo_projets/')),
                ('annee_creation', models.IntegerField()),
                ('is_rocket', models.BooleanField(default=False)),
                ('is_motor', models.BooleanField(default=False)),
                ('membres', models.ManyToManyField(through='myapi.MemberRole', to='myapi.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_fr', models.CharField(max_length=100, null=True)),
                ('nom_en', models.CharField(max_length=100, null=True)),
                ('priority', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('description_fr', models.CharField(max_length=1000, null=True)),
                ('description_en', models.CharField(max_length=1000, null=True)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='myapi/static/myapi/images/badges/')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_fr', models.CharField(max_length=100, null=True)),
                ('nom_en', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='myapi/static/myapi/images/logo_sponsors/')),
                ('link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('description_fr', models.CharField(max_length=1000, null=True)),
                ('description_en', models.CharField(max_length=1000, null=True)),
                ('projets', models.ManyToManyField(to='myapi.projet')),
            ],
        ),
        migrations.CreateModel(
            name='RocketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_status', models.CharField(max_length=255)),
                ('flight_status_fr', models.CharField(max_length=255, null=True)),
                ('flight_status_en', models.CharField(max_length=255, null=True)),
                ('years', models.CharField(max_length=255)),
                ('years_fr', models.CharField(max_length=255, null=True)),
                ('years_en', models.CharField(max_length=255, null=True)),
                ('number_members', models.IntegerField()),
                ('launch_date', models.CharField(max_length=255)),
                ('launch_date_fr', models.CharField(max_length=255, null=True)),
                ('launch_date_en', models.CharField(max_length=255, null=True)),
                ('launch_location', models.CharField(max_length=255)),
                ('launch_location_fr', models.CharField(max_length=255, null=True)),
                ('launch_location_en', models.CharField(max_length=255, null=True)),
                ('project_type', models.CharField(max_length=255)),
                ('project_type_fr', models.CharField(max_length=255, null=True)),
                ('project_type_en', models.CharField(max_length=255, null=True)),
                ('propulsion_type', models.CharField(max_length=255)),
                ('propulsion_type_fr', models.CharField(max_length=255, null=True)),
                ('propulsion_type_en', models.CharField(max_length=255, null=True)),
                ('diameter', models.CharField(max_length=255)),
                ('diameter_fr', models.CharField(max_length=255, null=True)),
                ('diameter_en', models.CharField(max_length=255, null=True)),
                ('length', models.CharField(max_length=255)),
                ('length_fr', models.CharField(max_length=255, null=True)),
                ('length_en', models.CharField(max_length=255, null=True)),
                ('exps', models.JSONField(default=list)),
                ('exps_fr', models.JSONField(default=list, null=True)),
                ('exps_en', models.JSONField(default=list, null=True)),
                ('exps_state', models.JSONField(default=list)),
                ('exps_state_fr', models.JSONField(default=list, null=True)),
                ('exps_state_en', models.JSONField(default=list, null=True)),
                ('prizes', models.JSONField(default=list)),
                ('prizes_fr', models.JSONField(default=list, null=True)),
                ('prizes_en', models.JSONField(default=list, null=True)),
                ('rocket_image', models.ImageField(blank=True, null=True, upload_to='myapi/static/myapi/images/rocket_images/')),
                ('rocket_styles', models.JSONField(default=dict)),
                ('rocket_styles_fr', models.JSONField(default=dict, null=True)),
                ('rocket_styles_en', models.JSONField(default=dict, null=True)),
                ('paragraph_array', models.JSONField(default=list)),
                ('paragraph_array_fr', models.JSONField(default=list, null=True)),
                ('paragraph_array_en', models.JSONField(default=list, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.projet')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='roles',
            field=models.ManyToManyField(through='myapi.MemberRole', to='myapi.role'),
        ),
        migrations.AddField(
            model_name='memberrole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.membre'),
        ),
        migrations.AddField(
            model_name='memberrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.projet'),
        ),
        migrations.AddField(
            model_name='memberrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.role'),
        ),
    ]
