# Generated by Django 4.2.7 on 2024-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='is_motor',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='is_rocket',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='nom_en',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='nom_fr',
        ),
        migrations.AlterField(
            model_name='membre',
            name='ok_to_be_displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='RocketDetail',
        ),
    ]
